spring.application.name=email-test

spring.datasource.url=jdbc:mysql://localhost:3306/email_test_3?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update


############### SMTP ############
email.property.host=smtp.gmail.com
email.property.port=587
email.property.emailId=amol64546@gmail.com
email.property.password=wiqj sdnw wift miod
email.property.provider=GMAIL
email.property.subject=Amol Nakhate